### PR TITLE
Fix cmake add_romdisk function

### PR DESCRIPTION
**Pull request by maishuji**
Hello, this is a fix proposal for the issue explained here :  https://github.com/KallistiOS/KallistiOS/issues/666
I compared it with the code from here, and made the change appropriately: https://github.com/KallistiOS/KallistiOS/blob/3f86969c5d4a0846a532823a208ea95a94879897/Makefile.rules#L73
I tested it on my project on linux

### CODE REVIEW

**Comment by pcercuei** [comment]
`cmake_add_romdisk` works perfectly fine in Bloom: https://github.com/pcercuei/bloom/blob/main/CMakeLists.txt#L318

I don't know what you are doing differently.

**Comment by maishuji** [comment]
> @maishuji I think what happens is that CMake won't compile romdisk.o from romdisk.c because your `project()` line says that it is exclusively C++.
> 
> If you write instead:
> 
> ```cmake
> project(dc-cmake-examples LANGUAGES C CXX)
> ```
> 
> It will most likely work.

Hello, I checked, yes it works without the fix, when adding C language support in CMakeLists.txt as you mentionned.
Is there any benefit to keep the original behavior compared to the fix proposal ? I don't think it is intuitive having to add C support in a full CXX project, so if it is possible isn't it better to avoid having to do it?

**Comment by pcercuei** [comment]
@maishuji see https://github.com/KallistiOS/KallistiOS/pull/677

**Comment by gyrovorbis** [comment]
> > @maishuji I think what happens is that CMake won't compile romdisk.o from romdisk.c because your `project()` line says that it is exclusively C++.
> > If you write instead:
> > ```cmake
> > project(dc-cmake-examples LANGUAGES C CXX)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It will most likely work.
> 
> Hello, I checked, yes it works without the fix, when adding C language support in CMakeLists.txt as you mentionned. Is there any benefit to keep the original behavior compared to the fix proposal ? I don't think it is intuitive having to add C support in a full CXX project, so if it is possible isn't it better to avoid having to do it?

Ughghghg. Yeah, you're right. That behavior does kind of suck and is counter-intuitive to how I'd expect CMake to work... but on the other hand, building it the other way breaks with LTO enabled...

Actually... hold on... Can't we make an internal static lib target that has nothing but that romdisk `.c` file in it, which gets added to the linked libs for the main target, completely transparently in that CMake utility function?

**Pull request closed without merging**
