### PR TITLE
Fix KOS + Examples when using LTO without -fno-builtins

### PR DESCRIPTION
**Pull request by gyrovorbis**
- LTO without `-fno-builtins` in the `environ.sh` has been broken for awhile.
- A slew of unresolved symbol errors are reported at linker time for every example.
- Had to manually include them within libkallisti.a via adding the `__used` pragma to their definitions.
- Confirmed to resolve the issue with GCC-14.1.0.

### CODE REVIEW

**Comment by pcercuei** [comment]
I'm not sure that's the *best* fix, since all used functions will be included in the binary even though they might be dead code.

**Comment by gyrovorbis** [comment]
> I'm not sure that's the _best_ fix, since all used functions will be included in the binary even though they might be dead code.

I can gate the assertion handler on NDEBUG,  but for the malloc/calloc/realloc/free, I mean... sure, but who isn't going to be using that stuff? Same with exit(), which might even get called in Newlib's exit path. I'm guessing all of this is used somewhere internally considering all of the examples seem to be failing with the same linker errors for these guys.

**Comment by pcercuei** [comment]
Did you try building Newlib with LTO support?

**Comment by gyrovorbis** [comment]
> Did you try building Newlib with LTO support?

...shit, on it. :)

**Comment by pcercuei** [comment]
>     * A slew of unresolved symbol errors are reported at linker time for every example.

For every example, really?

Apart from the atomics example, and some GL examples (because I don't have KGL installed it seems?), everything else builds fine here.

**Comment by gyrovorbis** [comment]
> > ```
> > * A slew of unresolved symbol errors are reported at linker time for every example.
> > ```
> 
> For every example, really?
> 
> Apart from the atomics example, and some GL examples (because I don't have KGL installed it seems?), everything else builds fine here.

WTF? I couldn't build *anything* like that without manually adding `__used` to those functions. Look at just the `hello` example:
```
falco@slutserv:/opt/toolchains/dc/kos/examples/dreamcast/hello$ make
rm -f hello.elf
kos-cc  -c hello.c -o hello.o
kos-cc -o hello.elf hello.o
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-exit.o): in function `exit':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/exit.c:65:(.text.exit+0x28): undefined reference to `_exit'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-dtoa.o): in function `dtoa_r':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/dtoa.c:751:(.text._dtoa_r+0x1150): undefined reference to `__assert_func'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o): in function `Balloc':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:134:(.text._Balloc+0x64): undefined reference to `_calloc_r'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o): in function `_multadd':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:186:(.text.__multadd+0xcc): undefined reference to `__assert_func'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o): in function `_i2b':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:329:(.text.__i2b+0x7c): undefined reference to `_calloc_r'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:329:(.text.__i2b+0x80): undefined reference to `__assert_func'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o): in function `_multiply':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:354:(.text.__multiply+0x20c): undefined reference to `__assert_func'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o): in function `_i2b':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:325:(.text.__pow5mult+0xf8): undefined reference to `__assert_func'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o): in function `_lshift':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:478:(.text.__lshift+0x154): undefined reference to `__assert_func'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o): in function `_mdiff':
/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:567:(.text.__mdiff+0x1d8): undefined reference to `__assert_func'
/opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/bin/ld: /opt/toolchains/dc/sh-elf/bin/../lib/gcc/sh-elf/14.1.0/../../../../sh-elf/lib/m4-single/libc.a(libc_a-mprec.o):/opt/toolchains/dc/kos/utils/dc-chain/build-newlib-sh-elf-4.4.0.20231231/sh-elf/m4-single/newlib/../../../../newlib-4.4.0.20231231/newlib/libc/stdlib/mprec.c:783: more undefined references to `__assert_func' follow
collect2: error: ld returned 1 exit status
make: *** [Makefile:34: hello.elf] Error 1
```

...unless... You aren't enabling release builds or defining `NDEBUG` in your `environ.sh` are you? Maybe all of this is just the exit path for assertion handling in debug builds?

**Comment by pcercuei** [comment]
Ooops, I think I actually was compiling with `-fno-builtin`...

One thing I'd like to know, is whether or not a function tagged as `__used` ends up in the final ELF, or if it's eventually stripped. From what I understand it forces the symbol to end up in the .o, but that doesn't mean that it gets to be in the final ELF.

**Comment by gyrovorbis** [comment]
> Ooops, I think I actually was compiling with `-fno-builtin`...
> 
> One thing I'd like to know, is whether or not a function tagged as `__used` ends up in the final ELF, or if it's eventually stripped. From what I understand it forces the symbol to end up in the .o, but that doesn't mean that it gets to be in the final ELF.

JESUS. I may have found the answer after a bunch of searching... Apparently `__used` only causes symbol emission during the compilation stage, and the symbol may still be stripped out after the linking stage... Which apparently is what this pragma, `retain` is for: https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#index-retain-function-attribute.

So I think this fix should be good and won't actually bloat the binary with unneeded functions. Should just be forcing them into `libkallisti`, but they can still be removed upon linking, if I understand correctly.

**Comment by pcercuei** [comment]
Ok, sounds good. I'll give it another try and report back.

**Comment by gyrovorbis** [comment]
> Ok, sounds good. I'll give it another try and report back.

Any update? Did it work for you now? You agree with the PR then?

**Comment by pcercuei** [comment]
> > Ok, sounds good. I'll give it another try and report back.
> 
> Any update? Did it work for you now? You agree with the PR then?

I'm on a road trip until probably next wednesday, will test then.

**Comment by gyrovorbis** [comment]
> > > Ok, sounds good. I'll give it another try and report back.
> > 
> > 
> > Any update? Did it work for you now? You agree with the PR then?
> 
> I'm on a road trip until probably next wednesday, will test then.

Ah, okay, have fun, man!!!

**Comment by pcercuei** [comment]
Ok, ACK. It fixes all the examples that had undefined references minus the atomic one.

**Review by darcagn — APPROVED** [review]

**Comment by pcercuei** [comment]
@darcagn @gyrovorbis btw `posix_memalign` seems to need a `__used` as well.

**Pull request merged**
