### PR TITLE
Using timer when not in preempt

### PR DESCRIPTION
**Pull request by QuzarDC**
This seems to fix the behavior of usleep in https://github.com/KallistiOS/KallistiOS/blob/1ea31b794b17c758087938cc97b529428fcf1d53/examples/dreamcast/libdream/320x240/320x240.c which is in coop threading mode. The idea is just to use the alternate timer method for sleeping when in any mode but preempt (as opposed to just when threading is not initted).

### CODE REVIEW

**Comment by ljsebald** [comment]
This does technically fix the problem of sleeping breaking entirely, but unfortunately, it also breaks the common assumption of cooperative multitasking -- that the process that is going to sleep gives up the CPU.

The process sleeping is holding onto the CPU in this case, which is not desirable.

**Comment by QuzarDC** [comment]
> This does technically fix the problem of sleeping breaking entirely, but unfortunately, it also breaks the common assumption of cooperative multitasking -- that the process that is going to sleep gives up the CPU.
> 
> The process sleeping is holding onto the CPU in this case, which is not desirable.

Oh, hah. Of course, that makes a lot of sense. I made another fix candidate. The idea is to pass at the end of the sleep after registering the gen wait which normally would just hang.

Need to write a bit of testing to see that it would actually sleep properly with another thread around and wait the appropriate amount of time before resuming execution.

**Comment by ljsebald** [comment]
I don't see how the second version here would fix the problem at hand?

My understanding of the situation is as follows:
1. In cooperative mode, the primary kernel timer is not set up to wake the scheduler.
2. The main thread tries to sleep, which causes the thread to be de-scheduled to wait in `genwait_wait()`, adding it to the timer queue. The only other two threads in the system are the reaper and the idle task. The reaper task is blocked waiting for a signal that it is needed, so the only task available to run is the idle task.
3. The idle task is scheduled and immediately calls `arch_sleep()`, which causes the CPU to sleep until an IRQ.
4. On next IRQ, the idle task is still in control (it has not asked to be de-scheduled), and immediately calls `arch_sleep()` again. This just repeats forever.

What might fix the situation (if my understanding there is correct) is having the idle task do a `thd_block_now(&thd_current->context);` each pass through the loop after `arch_sleep()`.

**Comment by QuzarDC** [comment]
That's how I had followed it too, but I presumed I had misunderstood and at some point it had to get to the thread reschedule after the gen wait because adding that *did* stop a program in coop mode from hanging on usleep. Though I'm totally on board with the consensus from #163 of just ditching coop mode entirely, I would like to understand why this managed to fix it (or maybe I just made a mistake somewhere?).

**Comment by ljsebald** [comment]
Mooted by #176.

**Pull request closed without merging**
