### PR TITLE
Make bin2o a little more robust.

### PR DESCRIPTION
**Pull request by jpeach**
- use a private directory for temporary files
- set shell error checking flags
- error on unsupported $KOS_ARCH settings

### CODE REVIEW

**Comment by gyrovorbis** [comment]
Anyone else think we should go ahead and remove the options for PS2 and GBA while we're at it? I didn't even realize they were still here, and we don't have any support for them anymore in the source tree...

**Comment by jpeach** [comment]
> 



> Anyone else think we should go ahead and remove the options for PS2 and GBA while we're at it? I didn't even realize they were still here, and we don't have any support for them anymore in the source tree...

Does that mean that $KOS_ARCH is also obsolete now?

**Comment by gyrovorbis** [comment]
> Does that mean that $KOS_ARCH is also obsolete now?
Pretty sure it does.

But pinging the Crabby one and Quzar to have them weigh-in. 

@ljsebald @QuzarDC

**Comment by QuzarDC** [comment]
The options for gba and ps2 were officially deprecated quite some time ago. I think the KOS_ARCH was left to keep the framework ready for additional architectures to be supported again.

I, for one, would love if ps2 or x86 were reintegrated.

**Comment by ljsebald** [comment]
I'd prefer not removing `$KOS_ARCH` for the same reason that @QuzarDC said it wasn't removed for -- the framework is there to bring other arches in, but there was nobody there to maintain them. If someone really wanted to, then I'd like it to be still possible to do so.

I don't think it really needs to be removed from this tool at the moment either, so I'm going to merge this as-is.

**Review by ljsebald — APPROVED** [review]

**Pull request merged**
