### PR TITLE
Add INSTALL.md

### PR DESCRIPTION
**Pull request by andressbarajas**
People on discord made a good point that KOS doesn't have install instructions in the repo. Its kinda weird that we dont. With all the other documentation updates that we are getting for the 2.1.0 release, I was hoping this one can join the bunch.  This is a stripped down rip-off of @darcagn 's work located here: https://dreamcast.wiki/Getting_Started_with_Dreamcast_development. Hopefully with his blessing we can include this in KOS.

### CODE REVIEW

**Comment by darcagn** [comment]
>People on discord made a good point that KOS doesn't have install instructions in the repo. Its kinda weird that we dont.

But we do. You are duplicating content already available in this repository here, written and formatted by myself and SiZiOUS, which is actually more comprehensive: https://github.com/KallistiOS/KallistiOS/tree/master/utils/dc-chain#readme

So I don't give permission to duplicate the dreamcast.wiki version into the KOS tree, given that it's intended to be an ever-changing document version, which is why I put effort into both   in-tree and out-of-tree sets of docs.

**Comment by andressbarajas** [comment]
I understand and accept that I don't have your permission to duplicate the dreamcast.wiki version into the KOS tree.

I didn't even know that we had the guide @  https://github.com/KallistiOS/KallistiOS/tree/master/utils/dc-chain#readme. I just took a look at it and its very comprehensive but it only covers dc-chain installation.  Its says to read https://github.com/KallistiOS/KallistiOS/blob/master/doc/README for further instructions but the readme doesn't cover compiling KOS.  Also most of the platform specific pages share the same instructions like:

```
mkdir -p /opt/toolchains/dc/
cd /opt/toolchains/dc/
git clone git://git.code.sf.net/p/cadcdev/kallistios kos
git clone git://git.code.sf.net/p/cadcdev/kos-ports
```

The installation info is scattered across various files, often containing duplicate instructions. I feel the dc-chain#readme you linked me to for installing KOS, toolchains, and kos-ports are either incomplete or unnecessarily complex, especially for newcomers. It presents more hurdles than the straightforward guide you're hosting, which is much easier to follow.

@darcagn, Do you think it would be easier for newcomers to setup kos, toolchain, and kos-ports using the guides hosted in this repo https://github.com/KallistiOS/KallistiOS/tree/master/utils/dc-chain#readme or do you think they would find it easier with your guide here: https://dreamcast.wiki/Getting_Started_with_Dreamcast_development ?

**Comment by ppxxcc** [comment]
The BUILDING section of doc/README should just be updated to make the instructions for building kos worded more clearly and then make a mention on how to build kos-ports. 

Also, commiting specific instructions for each distro/OS to the repo README is not a good idea since they change frequently enough that the specific instructions (especially package prereqs, which can change names or be merged into other packages across distro versions) will become obsolete upon system updates and will cause errors, confusing newcomers trying to follow the instructions, while experienced people won't realize since their system already has everything built.

**Comment by darcagn** [comment]
Remember KOS staff voted and determined to keep KOS structured platform agnostic, so in my docs PR that's how we were approaching the structure of the docs. The idea was to have links out to the per-platform toolchain building instructions in the main README.md [like here](https://github.com/KallistiOS/KallistiOS/blob/darc_docs_update/doc/README.md#prerequisites) (where it is only described for DC at the moment), then in describe how to build the platform agnostic parts (KOS itself, kos-ports which would be cross-platform, etc.) back in the KOS README.md [like here](https://github.com/KallistiOS/KallistiOS/blob/darc_docs_update/doc/README.md#building). (Side note, some of these blocks are out of order as quzar submitted the PR in a very WIP state)

> The installation info is scattered across various files, often containing duplicate instructions. I feel the dc-chain#readme you linked me to for installing KOS, toolchains, and kos-ports are either incomplete or unnecessarily complex, especially for newcomers. 

Yeah, the instructions in dc-chain (which I inherited from SiZiOUS but have been PRing revisions to over the past year+) have duplication per (host) platform, and still need further revision and streamlining. I spent days building toolchains, testing prereqs, updating prereqs on various distros/platforms/architectures, because some platforms like macOS and FreeBSD are moving targets with their own sets of quirks, and Windows stuff is such a tremendous (and slow...) PITA, and I even rewrote ~90% of dc-chain Makefiles from scratch to PR later for 2.2.0 after the feature freeze, but didn't have time to get the entirety of the docs in a state that I want it in -- it's difficult writing out this info into PR-sized chunks instead of incremental fast changes like one would have for a wiki.

> Do you think it would be easier for newcomers to setup kos, toolchain, and kos-ports using the guides hosted in this repo or do you think they would find it easier with your guide here

I think the KOS docs are in a very bad state and need a lot of improvement to make that easier for users, but ultimately I don't see them serving the exact same purpose, which again is why I have worked on both.

**Comment by andressbarajas** [comment]
> > Do you think it would be easier for newcomers to setup kos, toolchain, and kos-ports using the guides hosted in this repo or do you think they would find it easier with your guide here
> 
> I think the KOS docs are in a very bad state and need a lot of improvement to make that easier for users, but ultimately I don't see them serving the exact same purpose, which again is why I have worked on both.

Ultimately, what KOS needs is to **host** its own installation document that provides easy step-by-step instructions for installing the toolchain, kos, and kos-ports. That is the purpose of this PR, and it shouldn't be compared to the dc-chain#readme document you linked because, as you mentioned, they don't serve the exact same purpose. Since copying from https://dreamcast.wiki/Getting_Started_with_Dreamcast_development is out of the question, and since you've been in charge of this portion of KOS for a while and know it inside and out, what options remain? How can INSTALL.md be modified so that it doesn't copy your wiki and, at the same time, provides easy step-by-step instructions for installing the toolchain, kos, and kos-ports?

**Comment by cypressru** [comment]
> Also, commiting specific instructions for each distro/OS to the repo README is not a good idea since they change frequently enough that the specific instructions (especially package prereqs, which can change names or be merged into other packages across distro versions) will become obsolete as distros update and change which will cause errors, confusing newcomers trying to follow the instructions, while experienced people won't realize since their system already has everything built.

I don't know what a nice or clean solution would look like, but I can say that personally I like having required packages listed per os

**Comment by darcagn** [comment]
> Ultimately, what KOS needs is to **host** its own installation document that provides easy step-by-step instructions for installing the toolchain, kos, and kos-ports. That is the purpose of this PR, and it shouldn't be compared to the dc-chain#readme document you linked because, as you mentioned, they don't serve the exact same purpose. Since copying from https://dreamcast.wiki/Getting_Started_with_Dreamcast_development is out of the question, and since you've been in charge of this portion of KOS for a while and know it inside and out, what options remain? How can INSTALL.md be modified so that it doesn't copy your wiki and, at the same time, provides easy step-by-step instructions for installing the toolchain, kos, and kos-ports?

Sure, this repo **should** host its own installation instructions. I'm simply explaining what my plan for the docs was. I believe we should do this differently than what's here, by streamlining dc-chain docs to be simple and digestible and having the KOS-specific instructions in the README. But after re-reading your text, you stripped it down to the point where there's only a certain number of ways it can be said, and so I don't believe I should block you from having permission in merging this if that's what others agree to do here.

If this is merged as-is, the extraneous dependencies like meson should be removed and the typos fixed.

**Comment by sizious** [comment]
Jumping on this. I think that I share @darcagn point or view; while I think having an INSTALL file is pretty standard, I dislike the idea to have very detailed/specific instructions in that file.
I think something more generic, explaining the whole setup process and having redirections to existing docs could be more efficient from my point of view, something like:
- Setup the toolchains (redirect to dc-chain)
- Setup KOS (redirect to standard KOS instructions, like we did in dc-chain)
- Setup KOS Ports (optional but very interesting)
- Compiling examples

Off-topic:
Another stuff maybe missing is the whole workflow to describe how to make bootable discs, like using makeip/scramble/mkdcdisc or legacy tools like mine. Probably we will need to include mkdcdisc or another tool in the utils directory… I still have some work to contribute to that tool, but my children takes too much time 😅

**Comment by andressbarajas** [comment]
> I believe we should do this differently than what's here, by streamlining dc-chain docs to be simple and digestible and having the KOS-specific instructions in the README.

> I think something more generic, explaining the whole setup process and having redirections to existing docs could be more efficient from my point of view...

I disagree BUT I can understand your perspectives from an organization point of view with the documents. I just think it hurts more than it helps for newcomers.

My perspective is that by providing a single page with steps 1-10 for setup, it will leave little to no room for human error. I think https://dreamcast.wiki/Getting_Started_with_Dreamcast_development has worked wonders for onboarding new KOS users by taking this approach. I never heard any complaints from new users about the instructions.  It just works. Sure they may get compile errors time and again but those are platform specific issues.

Now you may be wondering where does that leave dc-chain#readme?  I think INSTALL.md and dc-chain#readme can coexist. Just like https://dreamcast.wiki/Getting_Started_with_Dreamcast_development and dc-chain#readme coexist now. dc-chain#readme gets more into the nitty-gritty and takes its time explaining and making sure the user knows what is being installed. It should exist for people who want to take a deeper dive into terms and really understanding the break down of the setup.  

Ultimately I think the goal should be to simplify the setup as much as possible by having it all on one page and stripping out the details most users will not care about when getting started. This lowers the bar for entry which means more people using KOS. I think we should all keep in mind that attention spans are getting shorter these days. Visiting multiple pages to set something up would just make things more frustrating, so it's better to keep everything in one clear and simple guide. Im hoping @QuzarDC enables the KOS repo wiki functionality so these instructions can live there instead of INSTALL.md.

> If this is merged as-is, the extraneous dependencies like meson should be removed and the typos fixed.

I'll do another review and strip out the extra dependencies, typos later today.

> Another stuff maybe missing is the whole workflow to describe how to make bootable discs, like using makeip/scramble/mkdcdisc or legacy tools like mine. Probably we will need to include mkdcdisc or another tool in the utils directory… I still have some work to contribute to that tool, but my children takes too much time 😅

100000% percent.  That should be the next main focus. Too many of our users are asking how to make .cdis.

**Comment by andressbarajas** [comment]
> If this is merged as-is, the extraneous dependencies like meson should be removed and the typos fixed.
I only found one typo "Hombrew" and removed the extraneous dependencies. Let me know if I missed anything.

**Comment by andressbarajas** [comment]
@sizious Here you go: https://github.com/KallistiOS/KallistiOS/pull/760

**Pull request closed without merging**
