### PR TITLE
renamed TMU0-2 to TIMER_UNIT_0-2 and timer_count to timer_get_count

### PR DESCRIPTION
**Pull request by gek169**
Every single instance. Consistency.
Needs a compile test to make sure it compiles to the exact same binary before the PR should be accepted.

### CODE REVIEW

**Comment by darcagn** [comment]
Closing PR for reasons discussed in Discord chat.

**Comment by gek169** [comment]
And, for reasons we discussed in discord chat, you will suffer for it. I promise.

**Comment by gek169** [comment]
For your disrespect and lying, let this project be accursed!

**Comment by andrewapperley** [comment]
> And, for reasons we discussed in discord chat, you will suffer for it. I promise.

You’re a piece of shit

**Pull request closed without merging**
