### PR TITLE
Thread-safe audio fixes

### PR DESCRIPTION
**Pull request by DC-SWAT**
- Fixes for streams mutex
- Added a spinlock for sound memory

### CODE REVIEW

**Review by gyrovorbis — APPROVED** [review]
Looks good! Just spent some time reviewing. Still want Crabby to see, but I didn't see anything wrong.

**Comment by ljsebald** [comment]
A big problem with doing this is that it makes it completely impossible to do any of the functions you've outfitted with mutexes from within an interrupt context (mutex_lock and mutex_lock_timed do not work in an interrupt context -- only mutex_trylock is available in an interrupt context). I'm definitely not comfortable with that restriction on the memory allocation.

Also introducing mutex locking within the sound polling functionality could potentially lead to issues with dropped samples and the like... I think we need to at least think about this a little bit more before taking this approach.

**Comment by DC-SWAT** [comment]
> A big problem with doing this is that it makes it completely impossible to do any of the functions you've outfitted with mutexes from within an interrupt context (mutex_lock and mutex_lock_timed do not work in an interrupt context -- only mutex_trylock is available in an interrupt context). I'm definitely not comfortable with that restriction on the memory allocation.

That's a good point, I didn't know about that. It can be remade, but I doubt that this will ever be called in interrupts; sound memory has a different use case.

> 
> Also introducing mutex locking within the sound polling functionality could potentially lead to issues with dropped samples and the like... I think we need to at least think about this a little bit more before taking this approach.

This is the main point, since it uses global resources such as buffer for PCM separation and the AICA DMA.
Separation buffer could be made for each stream, this would take up much more memory, but would be more thread-safe. It’s more complicated with the G2bus; this is only possible if you use different DMA channels or add a mutex for the AICA DMA channel.

**Comment by ljsebald** [comment]
> > A big problem with doing this is that it makes it completely impossible to do any of the functions you've outfitted with mutexes from within an interrupt context (mutex_lock and mutex_lock_timed do not work in an interrupt context -- only mutex_trylock is available in an interrupt context). I'm definitely not comfortable with that restriction on the memory allocation.
> 
> That's a good point, I didn't know about that. I'll rewrite this, but I doubt that this will ever be called in interrupts; sound memory has a different use case.
I agree that it is unlikely. Thank you for reworking it though.

> > Also introducing mutex locking within the sound polling functionality could potentially lead to issues with dropped samples and the like... I think we need to at least think about this a little bit more before taking this approach.
> 
> This is the main point, since it uses global resources such as buffer for PCM separation and the AICA DMA. Separation buffer could be made for each stream, this would take up much more memory, but would be more thread-safe. It’s more complicated with the G2bus; this is only possible if you use different DMA channels or add a mutex for the AICA DMA channel.
Ok... I can see the point there then. Thanks for the explanation as to what you were going for. I hadn't thought about that at all...

**Review by ljsebald — APPROVED** [review]

**Pull request merged**
