### PR TITLE
Add pvrtex utility

### PR DESCRIPTION
**Pull request by dfchil**
Adding the pvrtex tool by TapamN to KOS

### CODE REVIEW

**Comment by gyrovorbis** [comment]
This is fantastic. This tool will make a great addition to the KOS utilities and has been on the agenda for quite awhile, but nobody ever managed to make it happen. Thanks again!

**Comment by gyrovorbis** [comment]
> You should probably add a doc\CHANGELOG Entry like:
> 
> ```
> - *** Added support for one-shot timers [PC]
> - DC  Use one-shot timers for timeout and a proper polling mechanism in modem [PC]
> - *** Added pvrtex utility by TapamN to utils
> 
> KallistiOS version 2.0.0 -----------------------------------------------
> ```

Good call.
```
- *** Added pvrtex utility by TapamN to utils [DF=Daniel Fairchild]

**Comment by andressbarajas** [comment]
The changelog you added to this project is great and we should keep it but when mean KOS's changelog located in kos/docs/CHANGELOG.  Here: https://github.com/KallistiOS/KallistiOS/blob/master/doc/CHANGELOG.  At the end of the 2.1.0 section you can add:

`- *** Added pvrtex utility by TapamN to utils [DF == Daniel Fairchild]`

**Comment by andressbarajas** [comment]
Sorry, one more change. Can you add your folder name "pvrtex" to this makefile: https://github.com/KallistiOS/KallistiOS/blob/master/utils/Makefile

**Comment by andressbarajas** [comment]
I just pulled the code of this branch.  I got warnings when I compiled.  Can you fix them:

`l -I. -DCONFIG_MEMORY_POISONING=0 -DHAVE_FAST_UNALIGNED=0  -O3 -flto -c dither.cpp -o dither.o
dither.cpp:230:28: warning: unused variable 'map' [-Wunused-const-variable]
static const unsigned char map[8*8] = {
                           ^
dither.cpp:383:23: warning: unused variable 'pal' [-Wunused-const-variable]
static const unsigned pal[palettesize] = {
                      ^
2 warnings generated.`

**Comment by gyrovorbis** [comment]
Yo, guys, I'm unsure of where this PR fits in terms of the upcoming release.

On one hand, big-ass PR... On the other hand, this is a standalone tool that isn't going to be impacting the stability or testing/stabilization of the rest of the KOS library itself or anything, and this is single-handedly one of the most important tools that we are currently lacking as an SDK...

I'm more than happy to test the crap out of this personally and help get it ready to merge if we can still make it into 2.1.0. Seems worth it to me. If not, that's fine, we can do 2.2.0. Just wanted to see what people think.

**Comment by dfchil** [comment]
> Yo, guys, I'm unsure of where this PR fits in terms of the upcoming release.
> 
> On one hand, big-ass PR that we'd have to review/merge ontop of the other stuff... On the other hand, this is a standalone tool that isn't going to be impacting the stability or testing/stabilization of the rest of the KOS library itself or anything, and this is single-handedly one of the most important tools that we are currently lacking as an SDK...
> 
> I'm more than happy to test the crap out of this personally and help get it ready to merge if we can still make it into 2.1.0. Seems worth it to me. If not, that's fine, we can do 2.2.0. Just wanted to see what people think.

I'm happy either way. 

I'm actively using this PR as my KOS branch and have incorporated pvrtex into my build-setup. If it doesn't get merged for 2.1.0, I'll just keep manually updating this PR with changes from main until it does. 

But I do also agree with Falcos point that it can't possibly break anything as it, currently, is very standalone. 

Having it in 2.1.0 could also help garner more usage and hopefully more eyes on it and people either requesting new features or adding them on their own. 

Furthermore having it as this not-fully-incorporated part of 2.1.0 could also be a bais for streamling some of the examples that use textures to switch to pvrtex (typically from vqenc) and maybe even integrate the new DT header format that TapamN has deviced. I've already written such texture handling routines in my own code, and would be happy to contribute them to KOS when they are more mature. 

The above could equally also be an arugment for not putting the tool into 2.1.0 and just deliver it all in the next release, but I think low-key introducing it now is the better choice for the sake of developing kos further as a fully fledged toolchain.

**Comment by sizious** [comment]
Hey @dfchil, 
Thanks for this tool, very useful!

I tried to built it on [DreamSDK](https://dreamsdk.org/) but with no success:

    gcc  -flto=auto -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Ilibavutil -I. -DCONFIG_MEMORY_POISONING=0 -DHAVE_FAST_UNALIGNED=0 -I -I/opt/toolchains/dc/kos/include -I/opt/toolchains/dc/kos/kernel/arch/dreamcast/include -I/opt/toolchains/dc/kos/addons/include -I/opt/toolchains/dc/kos-ports/include -Wno-pointer-sign -O3 -flto -c file_dctex.c -o file_dctex.o
    In file included from file_dctex.h:12,
                     from file_dctex.c:5:
    C:/DreamSDK/msys/1.0/opt/toolchains/dc/kos/kernel/arch/dreamcast/include/dc/pvr.h:39:10: fatal error: sys/cdefs.h: No such file or directory
       39 | #include <sys/cdefs.h>
          |          ^~~~~~~~~~~~~
    compilation terminated.
    make: *** [file_dctex.o] Error 1

Removing this include in the `file_dctex.h` fixed the problem:

    #include <dc/pvr.h>

Do you know why this include has been added to this file?

Unfortunately, the `xxd' command is not available on [DreamSDK](https://dreamsdk.org/), but probably this is something I can fix on my side.

**Comment by dfchil** [comment]
> Hey @dfchil, Thanks for this tool, very useful!
> 
> I tried to built it on [DreamSDK](https://dreamsdk.org/) but with no success:
> 
> ```
> gcc  -flto=auto -Wall -Wextra -Wno-unused-parameter -Wno-sign-compare -Ilibavutil -I. -DCONFIG_MEMORY_POISONING=0 -DHAVE_FAST_UNALIGNED=0 -I -I/opt/toolchains/dc/kos/include -I/opt/toolchains/dc/kos/kernel/arch/dreamcast/include -I/opt/toolchains/dc/kos/addons/include -I/opt/toolchains/dc/kos-ports/include -Wno-pointer-sign -O3 -flto -c file_dctex.c -o file_dctex.o
> In file included from file_dctex.h:12,
>                  from file_dctex.c:5:
> C:/DreamSDK/msys/1.0/opt/toolchains/dc/kos/kernel/arch/dreamcast/include/dc/pvr.h:39:10: fatal error: sys/cdefs.h: No such file or directory
>    39 | #include <sys/cdefs.h>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make: *** [file_dctex.o] Error 1
> ```
> 
> Removing this include in the `file_dctex.h` fixed the problem:
> 
> ```
> #include <dc/pvr.h>
> ```
> 
> Do you know why this include has been added to this file?

Yes, I added it because I thought that reusing defines from pvr.h in kos would be a good thing when using file_dctex.h in projects for reading the new .DT format that pvrtex introduces. 
I've reconsidered that now, and removed `#include <dc/pvr.h>` from `file_dctex.h`.
Thank you very much for testing it and providing that feedback. 

> Unfortunately, the `xxd` command is not available on [DreamSDK](https://dreamsdk.org/), but probably this is something I can fix on my side.

I've added the two files header files generated with xxd to the repository. Their creation depends on the README file, so there is no need for most users to have to generate them. 

Hope that helps.

**Comment by sizious** [comment]
Hey @dfchil,

Thank you for the fix!

I just compiled the latest `xxd` from [Vim](https://github.com/vim/vim/), and now, everything is working!

**Review by sizious — APPROVED** [review]
Tested under [DreamSDK](https://dreamsdk.org/), this utility works perfectly.

**Review by gyrovorbis — APPROVED** [review]
Thank you so much for this and congratulations on becoming a KOS contributor! Huge deal tool here. About to go tell everyone about it!

**Pull request merged**
