### PR TITLE
Fix vmu_lcd compile error and extended vmu font API

### PR DESCRIPTION
**Pull request by andressbarajas**
Fix vmu_lcd example compile error by utilizing fontdata_4x6 and vmufb_font4x6 definitions in util/vmu_printf.c

### CODE REVIEW

**Review by QuzarDC — DISMISSED** [review]

**Comment by QuzarDC** [comment]
@gyrovorbis - Though this change could still stand, might it make sense to not have the font be extern, even if just to reduce possible name conflicts, and rely on the implemented API to get/set it? Could be the example also gets rewritten to demonstrate that usage.

**Comment by gyrovorbis** [comment]
> @gyrovorbis - Though this change could still stand, might it make sense to not have the font be extern, even if just to reduce possible name conflicts, and rely on the implemented API to get/set it? Could be the example also gets rewritten to demonstrate that usage.

Yeah. Then we should make that thing `static` again, and something to the API for `vmu_get_builtin_font()` which you can use to access it, otherwise, you can just overwrite it when changing the active font and never retrieve it again.

**Comment by andressbarajas** [comment]
@QuzarDC @gyrovorbis Implemented suggestions

**Comment by QuzarDC** [comment]
> > @gyrovorbis - Though this change could still stand, might it make sense to not have the font be extern, even if just to reduce possible name conflicts, and rely on the implemented API to get/set it? Could be the example also gets rewritten to demonstrate that usage.
> 
> Yeah. Then we should make that thing `static` again, and something to the API for `vmu_get_builtin_font()` which you can use to access it, otherwise, you can just overwrite it when changing the active font and never retrieve it again.

Aha, yup, that makes sense!

**Review by QuzarDC — APPROVED** [review]

**Pull request merged**
