### PR TITLE
Update GNU configs before dc-chain build

### PR DESCRIPTION
**Pull request by cepawiel**
This change downloads the newest versions of config.guess & config.sub into the dc-chain directory and then uses those files to replace any found in the downloaded sources. This should fix issues when building older releases on newer machines that the old scripts wouldn't recognize properly. Specifically this addresses the issue with GCC4.7 failing to build on ARM64 without updated config scripts.

TODO:
- [ ] Make sure `find` command is available on all supported dc-chain systems

### CODE REVIEW

**Comment by sizious** [comment]
I'm interested to contribute to this one, I have some changes that I want to implement in `dc-chain`. 😊

**Comment by cepawiel** [comment]
@sizious Didn't see this until now, sorry about that. Feel free to push to my branch and or fork, whatever is easiest for you. I was having trouble testing the build on Windows which is why I still had this in draft. Let me know if you need any testing or further help!

**Comment by darcagn** [comment]
These changes look good and so I resolved conflicts and marked ready for review so we can get movement on this PR.

**Review by QuzarDC — APPROVED** [review]
All ready. Just wanted to get an ok from @cepawiel since it had been left as a draft.

**Comment by cepawiel** [comment]
No objections from me!

**Pull request merged**
